services: 
 grafana:
  image: grafana/grafana-dev:10.3.0-152803
  container_name: grafana
  ports: 
   - "3000:3000"
  volumes:
   - grafanavol:/var/lib/grafana
  restart: unless-stopped
 
 prometheus:
  image: prom/prometheus:latest
  container_name: prometheus
  ports: 
   - "9090:9090"
  volumes:
   - promvol:/prometheus
   - /home/poseidon/Downloads/prom:/config
  command:
   - "--config.file=/config/prometheus.yaml"
  restart: unless-stopped
  
 nginx:
  image: nginx:latest
  container_name: nginx
  ports: 
   - "80:80"
  restart: unless-stopped
volumes:
 grafanavol:
 promvol:
